version: '3.8'

services:
  noshiro:
    build: ./
    container_name: noshiro
    environment:
      DISCORD_TOKEN: "youdiscordtoken"
      DEFAULT_PREFIX: "n."
      OWNER_IDS: ""
      LAVALINK_NODES: '[{"auth":"youshallnotpass","name":"Lava Docker","secure":false,"url":"lavalink:2333"}]'
    depends_on:
      - lavalink 
  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    configs:
      - source: lava
        target: /opt/Lavalink/application.yml

configs:
  lava:
    name: lava
    file: ./application.yml